version: 0.2

env:
  variables:
    SHELL: /bin/bash
    AWS_DEFAULT_REGION: eu-west-1
    APACHE_BASE_PATH: main
    ALTI_URL: //service-alti.dev.bgdi.ch
    API_URL: //mf-chsdi3.dev.bgdi.ch
    SHOP_URL: //shop-bgdi.dev.bgdi.ch
    DBHOST: pg-sandbox.bgdi.ch
    DBPORT: 5432
    DBSTAGING: dev
    DEPLOY_TARGET: dev
    GEODATA_STAGING: test
    GEOADMIN_FILE_STORAGE_BUCKET: public-dev-bgdi-ch
    GEOADMINHOST: mf-geoadmin3.dev.bgdi.ch
    HOST: mf-chsdi3.dev.bgdi.ch
    KEEP_VERSION: false
    WMTS_PUBLIC_HOST: tod.dev.bgdi.ch
    MODWSGI_CONFIG: production.ini
    PUBLIC_BUCKET_HOST: public.dev.bgdi.ch
    ROBOTS_FILE: robots.txt
    SERVER_PORT: 6543
    SPHINXHOST: service-sphinxsearch.dev.bgdi.ch
    VECTOR_BUCKET: bgdi-grid-based-data
    WMSHOST: wms-bgdi.dev.bgdi.ch
    WSGI_PROCESSES: 1
    WSGI_THREADS: 15
    CMSGEOADMINHOST: https://cms.geo.admin.ch
    LINKEDDATAHOST: https://ld.geo.admin.ch
    CACHE_CONTROL: no-cache
    USE_PYTHON3: 0
  parameter-store:
    OPENTRANS_API_KEY: "/terraform-codepipeline-example/opentrans_api_key"

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo "Installing softwares"

  pre_build:
    commands:
      - echo Configuring stuff...
      - aws --version
      - exec /bin/bash
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - GITHUB_BRANCH=${CODEBUILD_WEBHOOK_HEAD_REF#refs/heads/*}
      - TODAY=$(date '+%Y%m%d')
      - IMAGE_TAG=r_${TODAY}_${COMMIT_HASH}
      - COMPOSE_PROJECT_NAME=${IMAGE_TAG}
      - |-
           if [ "${CODEBUILD_WEBHOOK_TRIGGER}" = pr/* ]; then
             PULL_REQUEST=${CODEBUILD_WEBHOOK_TRIGGER#pr/*}
           fi
      - |-
           if [ "${GIT_BRANCH}" != master  ]; then
               LATEST=${GITHUB_BRANCH:-staging}
           else
               LATEST=latest
           fi
      - echo "=========== VERSIONS ============="
      - python --version
      - python2 --version
      - python3 --version
      - bash --version
      - echo "=========== VARIABLES ============="
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}
      - echo CODEBUILD_WEBHOOK_BASE_REF=${CODEBUILD_WEBHOOK_BASE_REF}
      - echo CODEBUILD_WEBHOOK_HEAD_REF=${CODEBUILD_WEBHOOK_HEAD_REF=}
      - echo CODEBUILD_WEBHOOK_TRIGGER=${CODEBUILD_WEBHOOK_TRIGGER}
      - echo CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}
      - echo CODEBUILD_BUILD_ID=${CODEBUILD_BUILD_ID}
      - echo CODEBUILD_SOURCE_REPO_URL=${CODEBUILD_SOURCE_REPO_URL}
      - echo COMMIT_HASH=${COMMIT_HASH}
      - echo PULL_REQUEST=${PULL_REQUEST}
      - echo GITHUB_BRANCH=${GITHUB_BRANCH}
      - echo IMAGE_TAG=${IMAGE_TAG}
      - echo BASH=${BASH}
      - echo SHELL=${SHELL}
      - echo "==================================="
  build:
    commands:
      - echo Build started on $(date)
      - make cleanall user
      - echo Build completed on $(date)
      
  post_build:
    commands:
      - echo Testing...
      - make lint
      - echo "Doing nothing, but great success"
