#
# Only for python3 and docker
#
version: 0.2

env:
  variables:
    SHELL: bash
    AWS_DEFAULT_REGION: eu-central-1
    SERVICE_NAME: "mf-chsdi3"
    DOCKER_REGISTRY: "974517877189.dkr.ecr.eu-central-1.amazonaws.com"
    USER: "aws_code_build"
    APACHE_BASE_PATH: main
    APACHE_PORT: 80
    ALTI_URL: //service-alti.dev.bgdi.ch
    API_URL: //mf-chsdi3.dev.bgdi.ch
    SHOP_URL: //shop-bgdi.dev.bgdi.ch
    DBHOST: pg-sandbox.bgdi.ch
    DBPORT: 5432
    DBSTAGING: dev
    DEPLOY_TARGET: dev
    GEODATA_STAGING: test
    GEOADMIN_FILE_STORAGE_BUCKET: mf-chsdi3-geoadmin-file-storage-bucket
    GEOADMIN_FILE_STORAGE_TABLE_NAME: mf_chsdi3_geoadmin_file_storage
    GEOADMIN_FILE_STORAGE_TABLE_REGION: eu-central-1
    GLSTYLES_STORAGE_TABLE_NAME: mf-chsdi3-vectortiles-styles-storage
    GLSTYLES_STORAGE_TABLE_REGION: eu-central-1
    GEOADMINHOST: mf-geoadmin3.dev.bgdi.ch
    HOST: mf-chsdi3.dev.bgdi.ch
    KEEP_VERSION: false
    WMTS_PUBLIC_HOST: tod.dev.bgdi.ch
    MODWSGI_CONFIG: production.ini
    PUBLIC_BUCKET_HOST: public.dev.bgdi.ch
    ROBOTS_FILE: robots.txt
    RANCHER_LABEL: dev
    SERVER_PORT: 80
    SPHINXHOST: service-sphinxsearch.dev.bgdi.ch
    VECTOR_BUCKET: mf-chsdi3-bgdi-grid-based-data
    WMSHOST: wms-bgdi.dev.bgdi.ch
    WSGI_PROCESSES: 1
    WSGI_THREADS: 15
    CMSGEOADMINHOST: https://cms.geo.admin.ch
    LINKEDDATAHOST: https://ld.geo.admin.ch
    CACHE_CONTROL: no-cache
    SHORTENER_TABLE_NAME: mf_chsdi3_shorturl
    SHORTENER_TABLE_REGION: eu-central-1
    SYSTEM_PYTHON_CMD: python3
    BUILD_TARGET: dev
    GIT_TAG: undefined
    # Disable some tests
    DYNAMODB_TESTS: 1
    S3_TESTS: 1
    # The all important USE_PYTHON3 variable is set by the AWS CodeBuild project
    # We do not have AWS S3 and DynmoDB access for now
  parameter-store:
    OPENTRANS_API_KEY: "/opentrans_api/key"
    PGUSER: "/postgresql/pguser"
    PGPASSWORD: "/postgresql/pgpassword"

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - aws --version

  pre_build:
    commands:
      - echo Configuring stuff...
      - aws --version
      - exec /bin/bash
      - echo "Login to AWS ECR docker registry"
      - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)

      # Reading git branch (the utility in the deploy script is unable to read it automatically
      # on CodeBuild)
      # see https://stackoverflow.com/questions/47657423/get-github-git-branch-for-aws-codebuild
      - export GITHUB_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
      - |-
        if [ "${GITHUB_BRANCH}" = "" ] ; then
          GITHUB_BRANCH="$(git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }')";
          export GITHUB_BRANCH=${GITHUB_BRANCH#remotes/origin/};
        fi
      - export PULL_REQUEST=${CODEBUILD_WEBHOOK_TRIGGER#pr/*}
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export GIT_TAG="$(git describe --tags || echo 'no version info')"
      - echo "GITHUB_BRANCH=${GITHUB_BRANCH} COMMIT_HASH=${COMMIT_HASH} GIT_TAG=${GIT_TAG}"

      - echo "=========== VERSIONS ============="
      - python --version
      - python2 --version
      - python3 --version
      - which python3
      - node --version
      - bash --version
      - echo "=========== VARIABLES ============="
      - echo CODEBUILD_RESOLVED_SOURCE_VERSION=${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - echo CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}
      - echo CODEBUILD_WEBHOOK_BASE_REF=${CODEBUILD_WEBHOOK_BASE_REF}
      - echo CODEBUILD_WEBHOOK_HEAD_REF=${CODEBUILD_WEBHOOK_HEAD_REF=}
      - echo CODEBUILD_WEBHOOK_TRIGGER=${CODEBUILD_WEBHOOK_TRIGGER}
      - echo CODEBUILD_SOURCE_VERSION=${CODEBUILD_SOURCE_VERSION}
      - echo CODEBUILD_BUILD_ID=${CODEBUILD_BUILD_ID}
      - echo CODEBUILD_SOURCE_REPO_URL=${CODEBUILD_SOURCE_REPO_URL}
      - echo COMMIT_HASH=${COMMIT_HASH}
      - echo PULL_REQUEST=${PULL_REQUEST}
      - echo GITHUB_BRANCH=${GITHUB_BRANCH}
      - echo BASH=${BASH}
      - echo SHELL=${SHELL}
      - echo CURRENT_DIRECTORY=$(pwd)
      - echo USE_PYTHON3=${USE_PYTHON3}
      - echo "===========POSGRESQL========================"
      - python ./scripts/pg_ready.py
      - hostname -I
      - make help
      - echo "==================================="
  build:
    commands:
      - echo Build started on $(date)
      - make cleanall all
      - |-
        if [ "${GIT_TAG}" = "undefined"  ] ; then
          DOCKER_IMG_TAG="${DOCKER_REGISTRY}/${SERVICE_NAME}:${GITHUB_BRANCH}.${COMMIT_HASH}"
        else
          DOCKER_IMG_TAG="${DOCKER_REGISTRY}/${SERVICE_NAME}:${GIT_TAG}"
        fi
      - export DOCKER_IMG_TAG=${DOCKER_IMG_TAG}
      - export DOCKER_IMG_TAG_LATEST="${DOCKER_REGISTRY}/${SERVICE_NAME}:${GITHUB_BRANCH}.latest"
      - echo "Building docker image with tags ${DOCKER_IMG_TAG} and ${DOCKER_IMG_TAG_LATEST}"
      - >
          docker build
          --build-arg GIT_HASH="${COMMIT_HASH}"
          --build-arg GIT_BRANCH="${GITHUB_BRANCH}"
          --build-arg AUTHOR="CI"
          --build-arg VERSION="${GIT_TAG}"
          -t "${DOCKER_IMG_TAG}" -t "${DOCKER_IMG_TAG_LATEST}" .
      - echo Build completed on $(date)
      - echo "===========SPHINXSEARCH===================="
      - .venv/bin/python ./scripts/test_sphinxserver.py
      - echo "==========Running tests=============="
      - make templates lint testci
      - docker-compose up -d
      - DOCKER_CONTAINER_ID=$(docker ps -aq --filter ancestor="${DOCKER_IMG_TAG_LATEST}")
      - echo "DOCKER_CONTAINER_ID=${DOCKER_CONTAINER_ID}"
      - docker logs ${DOCKER_CONTAINER_ID}
      - DOCKER_CONTAINER_ID=$(docker ps -aq --filter status="running" --filter ancestor="${DOCKER_IMG_TAG_LATEST}") && if [ -z "$DOCKER_CONTAINER_ID"  ]; then exit 1; fi
      - echo "Running test with the running container ${DOCKER_CONTAINER_ID}"
      - docker exec -i ${DOCKER_CONTAINER_ID} .venv/bin/nosetests  tests/functional
      - curl -s localhost:${SERVER_PORT}/rest/services/api/MapServer | jq -r '.layers[].layerBodId'

  post_build:
    commands:
      - test "$CODEBUILD_BUILD_SUCCEEDING" = "1"
      - echo "=========== Pushing image to repository ==========="
      - docker push ${DOCKER_IMG_TAG}
      - docker push ${DOCKER_IMG_TAG_LATEST}
      - echo "Done"

reports:
  reportGroupJunit:
    files:
      - 'junit-reports/**/*'
    file-format: JunitXml
