#!/bin/bash
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts
#            section in config file)
#

PROJECT_NAME=$1
CODE_DIR=$2

cd $CODE_DIR

echo "Target is: $TARGET"

if [[ $CODE_DIR == */branch/* ]]; then
  make -f Makefile.ireland clean
  make -f Makefile.ireland rc_branch DEPLOY_TARGET=$TARGET
  source rc_branch
  make -f Makefile.ireland templates
elif [[ -f rc_$TARGET ]]; then
  make -f Makefile.ireland clean
  source rc_$TARGET
  make -f Makefile.ireland templates
fi

exit $?
