#!/bin/bash
#
# variables set here:
#   $TARGET: name of the symbolic remote host key (see remote_hosts 
#            section in config file)
#

PROJECT_NAME=$1
CODE_DIR=$2

cd $CODE_DIR

echo "Target is: $TARGET"

if [[ $CODE_DIR == */branch/* ]]; then
  make clean
  make rc_branch DEPLOY_TARGET=$TARGET
  source rc_branch
  make templates
elif [[ -f rc_$TARGET ]]; then
  make clean
  source rc_$TARGET
  make templates
  make printwar APACHE_BASE_PATH=main
elif [[ "$TARGET" == "int_no_print" ]]; then
  make clean
  source rc_int
  make templates
elif [[ "$TARGET" == "prod_no_print" ]]; then
  make clean
  source rc_prod
  make templates
fi

exit $?
